source 'https://rubygems.org'

ruby '1.9.3'

gem 'rails', '4.0.2'

group :assets do
  gem 'sass-rails', '~> 4.0.0'
  gem 'coffee-rails', '~> 4.0.0'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'cancan'
gem 'devise'
gem 'figaro'
gem 'mysql2'
gem 'rolify'
gem 'simple_form'
#gem 'chosen-rails'
#gem "chartkick"
#gem 'groupdate'
#gem "active_median"
#gem 'uglifier', '>= 1.3.0'
#gem 'coffee-rails', '~> 4.0.0'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end
group :assets do
  gem 'less-rails'
  gem 'therubyracer', :platform=>:ruby
  gem 'twitter-bootstrap-rails'
end
group :development do
  gem 'better_errors'
  gem 'binding_of_caller', :platforms=>[:mri_19, :rbx]
  gem 'quiet_assets'
  #gem 'sqlite3'
  # gem 'pg'
  gem 'active_record_query_trace'
end
group :development, :test do
  gem 'factory_girl_rails'
  gem 'rspec-rails'
  gem 'thin'
  gem 'sqlite3'
end
group :production do
  #gem 'unicorn'
  gem "thin"
  gem 'pg'
end
group :test do
  gem 'capybara'
  gem 'cucumber-rails', :require=>false
  gem 'database_cleaner'
  gem 'email_spec'
  gem 'launchy'
end
