require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BenefitsController do

  # This should return the minimal set of attributes required to create a valid
  # Benefit. As you add validations to Benefit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BenefitsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all benefits as @benefits" do
      benefit = Benefit.create! valid_attributes
      get :index, {}, valid_session
      assigns(:benefits).should eq([benefit])
    end
  end

  describe "GET show" do
    it "assigns the requested benefit as @benefit" do
      benefit = Benefit.create! valid_attributes
      get :show, {:id => benefit.to_param}, valid_session
      assigns(:benefit).should eq(benefit)
    end
  end

  describe "GET new" do
    it "assigns a new benefit as @benefit" do
      get :new, {}, valid_session
      assigns(:benefit).should be_a_new(Benefit)
    end
  end

  describe "GET edit" do
    it "assigns the requested benefit as @benefit" do
      benefit = Benefit.create! valid_attributes
      get :edit, {:id => benefit.to_param}, valid_session
      assigns(:benefit).should eq(benefit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Benefit" do
        expect {
          post :create, {:benefit => valid_attributes}, valid_session
        }.to change(Benefit, :count).by(1)
      end

      it "assigns a newly created benefit as @benefit" do
        post :create, {:benefit => valid_attributes}, valid_session
        assigns(:benefit).should be_a(Benefit)
        assigns(:benefit).should be_persisted
      end

      it "redirects to the created benefit" do
        post :create, {:benefit => valid_attributes}, valid_session
        response.should redirect_to(Benefit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved benefit as @benefit" do
        # Trigger the behavior that occurs when invalid params are submitted
        Benefit.any_instance.stub(:save).and_return(false)
        post :create, {:benefit => { "title" => "invalid value" }}, valid_session
        assigns(:benefit).should be_a_new(Benefit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Benefit.any_instance.stub(:save).and_return(false)
        post :create, {:benefit => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested benefit" do
        benefit = Benefit.create! valid_attributes
        # Assuming there are no other benefits in the database, this
        # specifies that the Benefit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Benefit.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => benefit.to_param, :benefit => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested benefit as @benefit" do
        benefit = Benefit.create! valid_attributes
        put :update, {:id => benefit.to_param, :benefit => valid_attributes}, valid_session
        assigns(:benefit).should eq(benefit)
      end

      it "redirects to the benefit" do
        benefit = Benefit.create! valid_attributes
        put :update, {:id => benefit.to_param, :benefit => valid_attributes}, valid_session
        response.should redirect_to(benefit)
      end
    end

    describe "with invalid params" do
      it "assigns the benefit as @benefit" do
        benefit = Benefit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Benefit.any_instance.stub(:save).and_return(false)
        put :update, {:id => benefit.to_param, :benefit => { "title" => "invalid value" }}, valid_session
        assigns(:benefit).should eq(benefit)
      end

      it "re-renders the 'edit' template" do
        benefit = Benefit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Benefit.any_instance.stub(:save).and_return(false)
        put :update, {:id => benefit.to_param, :benefit => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested benefit" do
      benefit = Benefit.create! valid_attributes
      expect {
        delete :destroy, {:id => benefit.to_param}, valid_session
      }.to change(Benefit, :count).by(-1)
    end

    it "redirects to the benefits list" do
      benefit = Benefit.create! valid_attributes
      delete :destroy, {:id => benefit.to_param}, valid_session
      response.should redirect_to(benefits_url)
    end
  end

end
