require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FeaturedProductsController do

  # This should return the minimal set of attributes required to create a valid
  # FeaturedProduct. As you add validations to FeaturedProduct, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FeaturedProductsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all featured_products as @featured_products" do
      featured_product = FeaturedProduct.create! valid_attributes
      get :index, {}, valid_session
      assigns(:featured_products).should eq([featured_product])
    end
  end

  describe "GET show" do
    it "assigns the requested featured_product as @featured_product" do
      featured_product = FeaturedProduct.create! valid_attributes
      get :show, {:id => featured_product.to_param}, valid_session
      assigns(:featured_product).should eq(featured_product)
    end
  end

  describe "GET new" do
    it "assigns a new featured_product as @featured_product" do
      get :new, {}, valid_session
      assigns(:featured_product).should be_a_new(FeaturedProduct)
    end
  end

  describe "GET edit" do
    it "assigns the requested featured_product as @featured_product" do
      featured_product = FeaturedProduct.create! valid_attributes
      get :edit, {:id => featured_product.to_param}, valid_session
      assigns(:featured_product).should eq(featured_product)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FeaturedProduct" do
        expect {
          post :create, {:featured_product => valid_attributes}, valid_session
        }.to change(FeaturedProduct, :count).by(1)
      end

      it "assigns a newly created featured_product as @featured_product" do
        post :create, {:featured_product => valid_attributes}, valid_session
        assigns(:featured_product).should be_a(FeaturedProduct)
        assigns(:featured_product).should be_persisted
      end

      it "redirects to the created featured_product" do
        post :create, {:featured_product => valid_attributes}, valid_session
        response.should redirect_to(FeaturedProduct.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved featured_product as @featured_product" do
        # Trigger the behavior that occurs when invalid params are submitted
        FeaturedProduct.any_instance.stub(:save).and_return(false)
        post :create, {:featured_product => { "title" => "invalid value" }}, valid_session
        assigns(:featured_product).should be_a_new(FeaturedProduct)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FeaturedProduct.any_instance.stub(:save).and_return(false)
        post :create, {:featured_product => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested featured_product" do
        featured_product = FeaturedProduct.create! valid_attributes
        # Assuming there are no other featured_products in the database, this
        # specifies that the FeaturedProduct created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FeaturedProduct.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => featured_product.to_param, :featured_product => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested featured_product as @featured_product" do
        featured_product = FeaturedProduct.create! valid_attributes
        put :update, {:id => featured_product.to_param, :featured_product => valid_attributes}, valid_session
        assigns(:featured_product).should eq(featured_product)
      end

      it "redirects to the featured_product" do
        featured_product = FeaturedProduct.create! valid_attributes
        put :update, {:id => featured_product.to_param, :featured_product => valid_attributes}, valid_session
        response.should redirect_to(featured_product)
      end
    end

    describe "with invalid params" do
      it "assigns the featured_product as @featured_product" do
        featured_product = FeaturedProduct.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FeaturedProduct.any_instance.stub(:save).and_return(false)
        put :update, {:id => featured_product.to_param, :featured_product => { "title" => "invalid value" }}, valid_session
        assigns(:featured_product).should eq(featured_product)
      end

      it "re-renders the 'edit' template" do
        featured_product = FeaturedProduct.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FeaturedProduct.any_instance.stub(:save).and_return(false)
        put :update, {:id => featured_product.to_param, :featured_product => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested featured_product" do
      featured_product = FeaturedProduct.create! valid_attributes
      expect {
        delete :destroy, {:id => featured_product.to_param}, valid_session
      }.to change(FeaturedProduct, :count).by(-1)
    end

    it "redirects to the featured_products list" do
      featured_product = FeaturedProduct.create! valid_attributes
      delete :destroy, {:id => featured_product.to_param}, valid_session
      response.should redirect_to(featured_products_url)
    end
  end

end
